Rem ==============;
Rem Basic.bas;
Rem This is the example of RBasic Programming Language;
Rem RBasicTeam,All rights reserved 2017;
Rem Written by RBasicTeam 2017.11.18;
Rem ==============;
Start;
Hi>>greet;
ZHi>>greet2;
CPrint "A is:";
VPrint greet;
CPrint "B is:";
VPrint greet2;
eql:greet>>greet2;
compare:greet|greet2>>ans;
VPrint ans;