Rem ==============;
Rem Basic.bas;
Rem This is the example of RBasic Programming Language;
Rem RBasicTeam 2017;
Rem Written by RBasicTeam 2018.1.29;
Rem ==============;
Start;
Print "5";
Sleep 1;
Print "4";
Sleep 1;
Print "3";
Sleep 1;
Print "2";
Sleep 1;
Print "1";